# Generated by Django 5.1.3 on 2024-11-19 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercrud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.TextField(max_length=6)),
                ('doc_num', models.IntegerField(max_length=10)),
                ('first_name', models.TextField(max_length=30)),
                ('second_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=60)),
                ('name_origin', models.TextField()),
                ('birth_date', models.DateField()),
                ('gender', models.TextField(max_length=50)),
                ('cel_num', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
