# Generated by Django 5.1.3 on 2024-11-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercrud', '0002_userprofile_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cel_num',
            field=models.CharField(max_length=20),
        ),
    ]
